# Generated by Django 5.2.9 on 2026-03-05 11:34

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_sitesettings_menu_about_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Coupon', 'verbose_name_plural': 'Coupons'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ['sort_order'], 'verbose_name': 'Hero Slide', 'verbose_name_plural': 'Hero Slides'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='ordernote',
            options={'verbose_name': 'Order Note', 'verbose_name_plural': 'Order Notes'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Payment Method', 'verbose_name_plural': 'Payment Methods'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='salesdashboard',
            options={'managed': False, 'verbose_name': 'Sales Dashboard', 'verbose_name_plural': 'Sales Dashboard'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Wishlist', 'verbose_name_plural': 'Wishlist'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_zh_hant',
            field=models.CharField(max_length=100, null=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Coupon Code'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Value'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], default='percent', max_length=20, verbose_name='Discount Type'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(verbose_name='Valid To'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='Button Text'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='button_text_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Button Text'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='button_text_zh_hant',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Button Text'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(help_text='Recommended size: 1920x450 pixels (WxH)', upload_to='hero_slides/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='link',
            field=models.URLField(blank=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle_zh_hant',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title_zh_hant',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.coupon', verbose_name='Coupon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=100, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount Amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.paymentmethod', verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='Payment Proof'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('fulfilling', 'Fulfilling'), ('partially_shipped', 'Partially Shipped'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('returned', 'Returned'), ('refunded', 'Refunded')], default='created', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='is_customer_note',
            field=models.BooleanField(default=False, verbose_name='Sent to Customer'),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_notes', to='store.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_zh_hant',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_zh_hant',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='instructions',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Instructions'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='requires_proof',
            field=models.BooleanField(default=False, verbose_name='Requires Proof'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_zh_hant',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_zh_hant',
            field=models.CharField(max_length=200, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=100, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=220, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Specifications'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Specifications'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs_zh_hant',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Specifications'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact Address'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_address_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Address'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_address_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Address'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_opening_hours',
            field=models.CharField(blank=True, default='週一至週日: 10:00AM - 10:00PM', max_length=255, verbose_name='Opening Hours'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_opening_hours_en',
            field=models.CharField(blank=True, default='週一至週日: 10:00AM - 10:00PM', max_length=255, null=True, verbose_name='Opening Hours'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_opening_hours_zh_hant',
            field=models.CharField(blank=True, default='週一至週日: 10:00AM - 10:00PM', max_length=255, null=True, verbose_name='Opening Hours'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Contact Phone'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Feature Image'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='feature_subtitle',
            field=models.CharField(blank=True, default='加入我們對食物的精雕細琢之旅，感受我們的美食文化與獨特風格', max_length=500, verbose_name='Feature Subtitle'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='feature_subtitle_en',
            field=models.CharField(blank=True, default='加入我們對食物的精雕細琢之旅，感受我們的美食文化與獨特風格', max_length=500, null=True, verbose_name='Feature Subtitle'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='feature_subtitle_zh_hant',
            field=models.CharField(blank=True, default='加入我們對食物的精雕細琢之旅，感受我們的美食文化與獨特風格', max_length=500, null=True, verbose_name='Feature Subtitle'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='feature_title',
            field=models.CharField(blank=True, default='我們有什麽', max_length=200, verbose_name='Feature Title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='feature_title_en',
            field=models.CharField(blank=True, default='我們有什麽', max_length=200, null=True, verbose_name='Feature Title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='feature_title_zh_hant',
            field=models.CharField(blank=True, default='我們有什麽', max_length=200, null=True, verbose_name='Feature Title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_about',
            field=models.TextField(blank=True, verbose_name='Footer About'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_about_en',
            field=models.TextField(blank=True, null=True, verbose_name='Footer About'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_about_zh_hant',
            field=models.TextField(blank=True, null=True, verbose_name='Footer About'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_copyright',
            field=models.CharField(blank=True, default='Copyright © 2026 GWZ', max_length=200, verbose_name='Footer Copyright'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_copyright_en',
            field=models.CharField(blank=True, default='Copyright © 2026 GWZ', max_length=200, null=True, verbose_name='Footer Copyright'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_copyright_zh_hant',
            field=models.CharField(blank=True, default='Copyright © 2026 GWZ', max_length=200, null=True, verbose_name='Footer Copyright'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='founder_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Founder Image'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='founder_intro_text',
            field=models.TextField(blank=True, default='加入王子的美食之旅，享受生活中的美好事物！', verbose_name='Founder Intro Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='founder_intro_text_en',
            field=models.TextField(blank=True, default='加入王子的美食之旅，享受生活中的美好事物！', null=True, verbose_name='Founder Intro Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='founder_intro_text_zh_hant',
            field=models.TextField(blank=True, default='加入王子的美食之旅，享受生活中的美好事物！', null=True, verbose_name='Founder Intro Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='founder_intro_title',
            field=models.CharField(blank=True, default='平凡中見不凡', max_length=200, verbose_name='Founder Intro Title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='founder_intro_title_en',
            field=models.CharField(blank=True, default='平凡中見不凡', max_length=200, null=True, verbose_name='Founder Intro Title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='founder_intro_title_zh_hant',
            field=models.CharField(blank=True, default='平凡中見不凡', max_length=200, null=True, verbose_name='Founder Intro Title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='founder_name',
            field=models.CharField(blank=True, default='王子', max_length=100, verbose_name='Founder Name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='founder_name_en',
            field=models.CharField(blank=True, default='王子', max_length=100, null=True, verbose_name='Founder Name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='founder_name_zh_hant',
            field=models.CharField(blank=True, default='王子', max_length=100, null=True, verbose_name='Founder Name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_banner',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Hero Banner'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_button_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='Hero Button Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_button_text_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hero Button Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_button_text_zh_hant',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hero Button Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_link',
            field=models.URLField(blank=True, verbose_name='Hero Link'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Hero Subtitle'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hero Subtitle'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle_zh_hant',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hero Subtitle'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Hero Title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hero Title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title_zh_hant',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hero Title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_about_text',
            field=models.CharField(default='關於我們', max_length=50, verbose_name='Menu About Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_about_text_en',
            field=models.CharField(default='關於我們', max_length=50, null=True, verbose_name='Menu About Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_about_text_zh_hant',
            field=models.CharField(default='關於我們', max_length=50, null=True, verbose_name='Menu About Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_blog_text',
            field=models.CharField(default='博客', max_length=50, verbose_name='Menu Blog Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_blog_text_en',
            field=models.CharField(default='博客', max_length=50, null=True, verbose_name='Menu Blog Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_blog_text_zh_hant',
            field=models.CharField(default='博客', max_length=50, null=True, verbose_name='Menu Blog Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_contact_text',
            field=models.CharField(default='聯絡我們', max_length=50, verbose_name='Menu Contact Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_contact_text_en',
            field=models.CharField(default='聯絡我們', max_length=50, null=True, verbose_name='Menu Contact Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_contact_text_zh_hant',
            field=models.CharField(default='聯絡我們', max_length=50, null=True, verbose_name='Menu Contact Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_home_text',
            field=models.CharField(default='主頁', max_length=50, verbose_name='Menu Home Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_home_text_en',
            field=models.CharField(default='主頁', max_length=50, null=True, verbose_name='Menu Home Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_home_text_zh_hant',
            field=models.CharField(default='主頁', max_length=50, null=True, verbose_name='Menu Home Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_store_text',
            field=models.CharField(default='商店', max_length=50, verbose_name='Menu Store Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_store_text_en',
            field=models.CharField(default='商店', max_length=50, null=True, verbose_name='Menu Store Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_store_text_zh_hant',
            field=models.CharField(default='商店', max_length=50, null=True, verbose_name='Menu Store Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_tutorial_link',
            field=models.CharField(default='#', max_length=200, verbose_name='Menu Tutorial Link'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_tutorial_text',
            field=models.CharField(default='購物流程教學', max_length=50, verbose_name='Menu Tutorial Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_tutorial_text_en',
            field=models.CharField(default='購物流程教學', max_length=50, null=True, verbose_name='Menu Tutorial Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_tutorial_text_zh_hant',
            field=models.CharField(default='購物流程教學', max_length=50, null=True, verbose_name='Menu Tutorial Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='navbar_bg_color',
            field=models.CharField(default='#D32F2F', help_text='Hex color code (e.g. #D32F2F)', max_length=20, verbose_name='Navbar Bg Color'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='navbar_items',
            field=models.TextField(default='HP, CANON, BROTHER, EPSON, SAMSUNG, XEROX, PANTUM, LEXMARK, KODAK, 其他商品', help_text='Comma separated list', verbose_name='Navbar Items'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='navbar_items_en',
            field=models.TextField(default='HP, CANON, BROTHER, EPSON, SAMSUNG, XEROX, PANTUM, LEXMARK, KODAK, 其他商品', help_text='Comma separated list', null=True, verbose_name='Navbar Items'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='navbar_items_zh_hant',
            field=models.TextField(default='HP, CANON, BROTHER, EPSON, SAMSUNG, XEROX, PANTUM, LEXMARK, KODAK, 其他商品', help_text='Comma separated list', null=True, verbose_name='Navbar Items'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='navbar_text_color',
            field=models.CharField(default='#ffffff', help_text='Hex color code (e.g. #ffffff)', max_length=20, verbose_name='Navbar Text Color'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_label_bg_color',
            field=models.CharField(default='#D32F2F', max_length=20, verbose_name='Product Label Bg Color'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_label_text_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='Product Label Text Color'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='My E-Shop', max_length=100, verbose_name='Site Name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name_en',
            field=models.CharField(default='My E-Shop', max_length=100, null=True, verbose_name='Site Name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name_zh_hant',
            field=models.CharField(default='My E-Shop', max_length=100, null=True, verbose_name='Site Name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='smtp_from_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='From Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=200, verbose_name='SMTP Host'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=200, verbose_name='SMTP Password'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='smtp_port',
            field=models.IntegerField(default=587, verbose_name='SMTP Port'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, verbose_name='Use TLS'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='smtp_user',
            field=models.CharField(blank=True, max_length=200, verbose_name='SMTP User'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='top_bar_bg_color',
            field=models.CharField(default='#F50057', help_text='Hex color code (e.g. #F50057)', max_length=20, verbose_name='Top Bar Bg Color'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_url',
            field=models.URLField(blank=True, verbose_name='WhatsApp URL'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added At'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='store.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
