# Generated by Django 5.2.9 on 2026-03-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_category_options_alter_coupon_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_playlist_url',
            field=models.URLField(blank=True, default='https://www.youtube.com/embed/videoseries?list=PLEjO4hD4At7yhmox4RhnjRWaUujB24TZ2', help_text='Embed URL for the playlist', verbose_name='YouTube Playlist URL'),
        ),
    ]
