# Generated by Django 5.2.9 on 2026-03-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_sitesettings_youtube_playlist_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='menu_blog_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='menu_blog_text_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='menu_blog_text_zh_hant',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_lifestyle_text',
            field=models.CharField(default='味覺足跡', max_length=50, verbose_name='Menu Lifestyle Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_lifestyle_text_en',
            field=models.CharField(default='味覺足跡', max_length=50, null=True, verbose_name='Menu Lifestyle Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_lifestyle_text_zh_hant',
            field=models.CharField(default='味覺足跡', max_length=50, null=True, verbose_name='Menu Lifestyle Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_videos_text',
            field=models.CharField(default='王子煮場', max_length=50, verbose_name='Menu Videos Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_videos_text_en',
            field=models.CharField(default='王子煮場', max_length=50, null=True, verbose_name='Menu Videos Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_videos_text_zh_hant',
            field=models.CharField(default='王子煮場', max_length=50, null=True, verbose_name='Menu Videos Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_about_text',
            field=models.CharField(default='關於GWZ', max_length=50, verbose_name='Menu About Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_about_text_en',
            field=models.CharField(default='關於GWZ', max_length=50, null=True, verbose_name='Menu About Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_about_text_zh_hant',
            field=models.CharField(default='關於GWZ', max_length=50, null=True, verbose_name='Menu About Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_home_text',
            field=models.CharField(default='首頁', max_length=50, verbose_name='Menu Home Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_home_text_en',
            field=models.CharField(default='首頁', max_length=50, null=True, verbose_name='Menu Home Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_home_text_zh_hant',
            field=models.CharField(default='首頁', max_length=50, null=True, verbose_name='Menu Home Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_store_text',
            field=models.CharField(default='GWZ商店', max_length=50, verbose_name='Menu Store Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_store_text_en',
            field=models.CharField(default='GWZ商店', max_length=50, null=True, verbose_name='Menu Store Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_store_text_zh_hant',
            field=models.CharField(default='GWZ商店', max_length=50, null=True, verbose_name='Menu Store Text'),
        ),
    ]
