# Generated by Django 5.2.9 on 2026-03-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_product_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='top_bar_bg_color',
            field=models.CharField(default='#5D2E86', help_text='Hex color code (e.g. #5D2E86)', max_length=20, verbose_name='Top Bar Bg Color'),
        ),
    ]
