# Generated by Django 5.2.9 on 2026-03-08 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_sitesettings_youtube_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='menu_tutorial_link',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='menu_tutorial_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='menu_tutorial_text_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='menu_tutorial_text_zh_hant',
        ),
    ]
