# Generated by Django 5.2.9 on 2026-03-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_remove_sitesettings_menu_tutorial_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='navbar_bg_color',
            field=models.CharField(default='#5D2E86', help_text='Hex color code (e.g. #5D2E86)', max_length=20, verbose_name='Navbar Bg Color'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_label_bg_color',
            field=models.CharField(default='#5D2E86', max_length=20, verbose_name='Product Label Bg Color'),
        ),
    ]
