# Generated by Django 5.2.9 on 2026-03-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_remove_sitesettings_contact_address_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Feature Image'),
        ),
        migrations.AddField(
            model_name='page',
            name='feature_subtitle',
            field=models.CharField(blank=True, max_length=500, verbose_name='Feature Subtitle'),
        ),
        migrations.AddField(
            model_name='page',
            name='feature_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Feature Title'),
        ),
        migrations.AddField(
            model_name='page',
            name='founder_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Founder Image'),
        ),
        migrations.AddField(
            model_name='page',
            name='founder_intro_text',
            field=models.TextField(blank=True, verbose_name='Founder Intro Text'),
        ),
        migrations.AddField(
            model_name='page',
            name='founder_intro_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Founder Intro Title'),
        ),
        migrations.AddField(
            model_name='page',
            name='founder_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Founder Name'),
        ),
    ]
