# Generated by Django 5.2.9 on 2026-03-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_page_feature_image_page_feature_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesdashboard',
            options={'managed': False, 'verbose_name': '銷售報表', 'verbose_name_plural': '銷售報表'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_zh_hant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_zh_hant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_zh_hant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specs_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specs_zh_hant',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_share_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200x1200px (Square) for WhatsApp/Facebook previews', null=True, upload_to='site/', verbose_name='Social Share Image'),
        ),
    ]
