# Generated by Django 5.2.9 on 2026-03-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_alter_salesdashboard_options_remove_category_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='social_share_image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200x1200px (Square) for WhatsApp/Facebook previews', null=True, upload_to='site/', verbose_name='Social Share Image'),
        ),
    ]
