# Generated by Django 5.2.9 on 2026-03-09 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_pagevisit_country_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackupManager',
        ),
    ]
