"""
Django settings for eshop project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-v6x*@kixnzxju&6_rf1u1vec_du8a4(nrqrxmpomqe!c+d^f!%')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost:8000,http://127.0.0.1:8000').split(',')

LOGIN_REDIRECT_URL = 'product_list'
LOGOUT_REDIRECT_URL = 'product_list'
LOGIN_URL = 'login'

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django_recaptcha',
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'ckeditor',
    'axes',
    'import_export',
    'store',
    'analytics',
    'dbbackup',
    'backup_manager',
]

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# Database Backup Settings
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
    "dbbackup": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": BASE_DIR / 'backups',
        },
    },
}

# Email Configuration
EMAIL_BACKEND = 'store.email_backend.DatabaseEmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@gwz.one'
ADMIN_EMAIL = 'admin@gwz.one'

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'store.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

SITE_ID = 1

# Axes Configuration
AXES_FAILURE_LIMIT = 100
AXES_COOLOFF_TIME = 0.1  # 6 minutes? No, let's make it very short or hours. 0.1 is usually hours.
# Wait, AXES_COOLOFF_TIME is in hours by default in older versions, or minutes in newer?
# Let's check docs or source if possible. Usually it's hours.
# But AXES_RESET_ON_SUCCESS = True is default.

# Security Settings
# SSL/HTTPS (Enable these in production)
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
    'analytics.middleware.AnalyticsMiddleware',
]

ROOT_URLCONF = 'gwz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'store.context_processors.site_settings',
                'store.context_processors.cart_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'gwz.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hant'

LANGUAGES = [
    ('zh-hant', _('Traditional Chinese')),
    ('en', _('English')),
]

MODELTRANSLATION_DEFAULT_LANGUAGE = 'zh-hant'
MODELTRANSLATION_FALLBACK_LANGUAGES = {
    'default': ('zh-hant', 'en'),
    'en': ('zh-hant',),
    'zh-hant': ('en',)
}

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'Asia/Hong_Kong'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Stripe Configuration (set environment variables in production)
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY')
STRIPE_ENABLED = bool(STRIPE_PUBLISHABLE_KEY and STRIPE_SECRET_KEY)

# Recaptcha Test Keys (Development)
RECAPTCHA_PUBLIC_KEY = '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI'
RECAPTCHA_PRIVATE_KEY = '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe'
SILENCED_SYSTEM_CHECKS = ['django_recaptcha.recaptcha_test_key_error']

# Jazzmin Settings
JAZZMIN_SETTINGS = {
    "site_title": "GWZ Admin",
    "site_header": "GWZ",
    "site_brand": "GWZ",
    "site_logo": "img/logo.png",
    "login_logo": "img/logo.png",
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": "img/logo.png",
    "welcome_sign": "Welcome to GWZ Admin",
    "copyright": "GWZ",
    "search_model": "auth.User",
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Site", "url": "product_list", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": ["axes", "sites"],
    "hide_models": ["auth.Group", "backup_manager.Backup", "socialaccount.SocialApp", "socialaccount.SocialAccount", "account.EmailAddress"],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "store.Customer": "fas fa-user-friends",
        "store.Order": "fas fa-shopping-cart",
        "store.SalesDashboard": "fas fa-chart-line",
        "analytics.ShopStatistics": "fas fa-chart-bar",
        "store.Category": "fas fa-tags",
        "store.Product": "fas fa-box-open",
        "store.SiteSettings": "fas fa-cogs",
        "store.Page": "fas fa-file-alt",
        "store.HeroSlide": "fas fa-images",
        "store.PaymentMethod": "fas fa-credit-card",
        "store.Coupon": "fas fa-ticket-alt",
    },
    "order_with_respect_to": [
        # Store App (First)
        "store",
        "store.Customer",
        "store.Order",
        "store.SalesDashboard",
        "store.Category",
        "store.Product",
        "store.SiteSettings",
        "store.Page",
        "store.HeroSlide",
        "store.PaymentMethod",
        "store.Coupon",
        
        # Analytics App
        "analytics",
        "analytics.ShopStatistics",
        "analytics.BackupManager",
        
        # Auth App
        "auth",
        "auth.User",
        "auth.Group",
        
        # Backup Manager App
        "backup_manager",
        "backup_manager.Backup",
        
        # Axes App (Last)
        "axes",
        "axes.AccessAttempt",
        "axes.AccessFailureLog",
        "axes.AccessLog",
        "axes.AccessAttemptExpiration",
    ],
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": None,
    "custom_js": None,
    "show_ui_builder": False,
    "changeform_format_overrides": {"store.product": "single"},
}
